/**
 * Hand-written to match supabase/migrations/20260804150000_init.sql.
 *
 * Once the migration is applied you can regenerate this file instead of
 * maintaining it by hand:
 *   npx supabase gen types typescript --project-id <ref> > src/lib/database.types.ts
 */

export type GenderCategory = "male" | "female";
/**
 * An open, academy-managed list (see `CircleTypeOption` and the `circle_types`
 * table), not a fixed set — an admin can add one at any time from
 * /admin/circle-types, so this cannot be a literal union.
 */
export type CircleType = string;
export type AttendanceStatus = "pending" | "present" | "absent";
export type RecitationStatus = "waiting" | "reciting" | "done";
export type TeacherRole = "teacher" | "admin";

export type Academy = {
  id: string;
  slug: string;
  name_ar: string;
  name_en: string;
  description_ar: string | null;
  description_en: string | null;
  logo_path: string | null;
  primary_color: string;
  accent_color: string;
  is_active: boolean;
  created_at: string;
};

export type Teacher = {
  id: string;
  auth_user_id: string | null;
  name: string;
  phone: string | null;
  /** Digits-only form of the phone, generated by the DB. Unique per academy. */
  phone_key: string | null;
  gender_category: GenderCategory;
  role: TeacherRole;
  is_active: boolean;
  academy_id: string;
  created_at: string;
};

export type Student = {
  id: string;
  name: string;
  father_name: string;
  phone: string | null;
  /** Digits-only form of `phone`, generated by the DB. Unique per academy. */
  phone_key: string | null;
  gender_category: GenderCategory;
  search_key: string;
  academy_id: string;
  created_at: string;
};

export type Circle = {
  id: string;
  teacher_id: string;
  name: string;
  type: CircleType;
  gender_category: GenderCategory;
  session_link: string;
  timezone: string;
  start_time: string;
  duration_minutes: number;
  /** PostgreSQL dow convention: 0 = Sunday … 6 = Saturday. */
  days_of_week: number[];
  registration_slug: string;
  is_active: boolean;
  academy_id: string;
  created_at: string;
};

export type AttendanceRecord = {
  id: string;
  student_id: string;
  circle_id: string;
  session_date: string;
  queue_order: number;
  joined_at: string;
  attendance_status: AttendanceStatus;
  recitation_status: RecitationStatus;
  created_at: string;
};

export type CirclePublicInfo = {
  id: string;
  name: string;
  type: CircleType;
  gender_category: GenderCategory;
  session_link: string;
  start_time: string;
  timezone: string;
  session_date: string;
  meets_today: boolean;
  academy_id: string;
};

export type StudentSearchResult = {
  id: string;
  name: string;
  father_name: string;
};

export type JoinCircleResult = {
  attendance_id: string;
  session_date: string;
  queue_order: number;
  already_joined: boolean;
};

export type QueueEntry = {
  attendance_id: string;
  student_id: string;
  name: string;
  father_name: string;
  queue_order: number;
  attendance_status: AttendanceStatus;
  recitation_status: RecitationStatus;
  joined_at: string;
};

export type TeacherTodayCircle = {
  id: string;
  name: string;
  type: CircleType;
  gender_category: GenderCategory;
  start_time: string;
  timezone: string;
  registration_slug: string;
  session_date: string;
  joined_count: number;
};

/** Confirms a name + phone match. Deliberately carries nothing else. */
export type TeacherLoginMatch = {
  teacher_id: string;
  is_active: boolean;
};

export type CircleTypeOption = {
  id: string;
  academy_id: string;
  slug: string;
  name_ar: string;
  name_en: string;
  is_active: boolean;
  created_at: string;
};

/**
 * One published table on the public schedule page. Holds presentation only —
 * the days and names it renders are read live from `circles`.
 */
/**
 * What `academy_schedule` returns: an active circle as the public timetable
 * may see it — no `session_link`, and the teacher's name already joined in.
 */
export type ScheduleCircle = {
  id: string;
  name: string;
  type: CircleType;
  gender_category: GenderCategory;
  start_time: string;
  timezone: string;
  days_of_week: number[];
  registration_slug: string;
  teacher_name: string;
};

export type ScheduleBoard = {
  id: string;
  academy_id: string;
  circle_type: CircleType;
  /** Null covers both sections. */
  gender_category: GenderCategory | null;
  /**
   * Inclusive HH:MM bounds on a circle's `start_time`, each optional and each
   * open-ended alone — this is what separates a "2ظ" board from a "5م" one
   * when both cover the same circle type.
   */
  start_from: string | null;
  start_to: string | null;
  title_ar: string;
  title_en: string;
  note_ar: string | null;
  note_en: string | null;
  display_order: number;
  is_published: boolean;
  created_at: string;
};

export type AttendanceReportRow = {
  student_id: string;
  student_name: string;
  father_name: string;
  gender_category: GenderCategory;
  sessions_joined: number;
  sessions_recited: number;
  sessions_not_recited: number;
};

type Insert<T, Optional extends keyof T> = Omit<T, Optional> &
  Partial<Pick<T, Optional>>;

/** Matches Supabase's generated shape: every table needs a Relationships key. */
type Empty = { [_ in never]: never };

export type Database = {
  public: {
    Tables: {
      academies: {
        Row: Academy;
        Insert: Insert<Academy, "id" | "created_at" | "is_active" | "description_ar" | "description_en" | "logo_path">;
        Update: Partial<Academy>;
        Relationships: [];
      };
      teachers: {
        Row: Teacher;
        // `phone_key` is a generated column — never written.
        Insert: Insert<
          Teacher,
          "id" | "created_at" | "role" | "is_active" | "auth_user_id" | "phone_key"
        >;
        Update: Partial<Teacher>;
        Relationships: [];
      };
      students: {
        Row: Student;
        // `search_key` and `phone_key` are generated columns — never written.
        Insert: Insert<
          Student,
          "id" | "created_at" | "search_key" | "phone_key" | "academy_id"
        >;
        Update: Partial<Student>;
        Relationships: [];
      };
      circles: {
        Row: Circle;
        Insert: Insert<
          Circle,
          "id" | "created_at" | "is_active" | "timezone" | "duration_minutes" | "days_of_week" | "academy_id"
        >;
        Update: Partial<Circle>;
        Relationships: [];
      };
      attendance_records: {
        Row: AttendanceRecord;
        // Rows are created only by join_circle(); no RLS policy allows a direct
        // insert, so this type exists to satisfy the client, not to be used.
        Insert: Insert<AttendanceRecord, "id" | "created_at" | "joined_at">;
        Update: Partial<
          Pick<AttendanceRecord, "attendance_status" | "recitation_status" | "queue_order">
        >;
        Relationships: [];
      };
      circle_types: {
        Row: CircleTypeOption;
        Insert: Insert<CircleTypeOption, "id" | "created_at" | "is_active">;
        Update: Partial<CircleTypeOption>;
        Relationships: [];
      };
      schedule_boards: {
        Row: ScheduleBoard;
        Insert: Insert<
          ScheduleBoard,
          "id" | "created_at" | "is_published" | "display_order"
        >;
        Update: Partial<ScheduleBoard>;
        Relationships: [];
      };
    };
    Views: Empty;
    Functions: {
      get_academy: {
        Args: { p_slug: string };
        Returns: Academy[];
      };
      circle_public_info: {
        Args: { p_slug: string };
        Returns: CirclePublicInfo[];
      };
      academy_schedule: {
        Args: { p_academy_id: string };
        Returns: ScheduleCircle[];
      };
      search_students: {
        Args: { p_slug: string; p_query: string };
        Returns: StudentSearchResult[];
      };
      find_similar_students: {
        Args: { p_name: string; p_father_name: string; p_gender: GenderCategory; p_academy_id: string };
        Returns: StudentSearchResult[];
      };
      join_circle: {
        Args: { p_slug: string; p_student_id: string };
        Returns: JoinCircleResult[];
      };
      circle_queue: {
        Args: { p_slug: string };
        Returns: QueueEntry[];
      };
      teacher_today_circles: {
        Args: Record<PropertyKey, never>;
        Returns: TeacherTodayCircle[];
      };
      reorder_queue: {
        Args: {
          p_circle_id: string;
          p_session_date: string;
          p_student_ids: string[];
        };
        Returns: undefined;
      };
      teacher_login: {
        Args: { p_academy_id: string; p_name: string; p_phone: string };
        Returns: TeacherLoginMatch[];
      };
      link_teacher_auth: {
        Args: { p_teacher_id: string };
        Returns: undefined;
      };
      register_teacher: {
        Args: {
          p_academy_id: string;
          p_name: string;
          p_phone: string;
          p_role: TeacherRole;
          p_gender?: GenderCategory;
        };
        Returns: undefined;
      };
      attendance_report: {
        Args: {
          p_from: string;
          p_to: string;
          p_gender?: GenderCategory | null;
          p_circle_id?: string | null;
          p_teacher_id?: string | null;
          p_academy_id?: string | null;
          p_circle_type?: CircleType | null;
        };
        Returns: AttendanceReportRow[];
      };
    };
    Enums: Empty;
    CompositeTypes: Empty;
  };
};
