/**
 * Hand-written to match supabase/migrations/20260804150000_init.sql.
 *
 * Once the migration is applied you can regenerate this file instead of
 * maintaining it by hand:
 *   npx supabase gen types typescript --project-id <ref> > src/lib/database.types.ts
 */

export type GenderCategory = "male" | "female";
/**
 * An open, academy-managed list (see `CircleTypeOption` and the `circle_types`
 * table), not a fixed set — an admin can add one at any time from
 * /admin/circle-types, so this cannot be a literal union.
 */
export type CircleType = string;
export type AttendanceStatus = "pending" | "present" | "absent";
export type RecitationStatus = "waiting" | "reciting" | "done";
/**
 * The value of the legacy `teachers.role` column. It is derived from `roles`
 * by a database trigger and kept only for display — never write it, and never
 * decide a permission from it. Use `roles` and the helpers in `auth/roles.ts`.
 */
export type TeacherRole = "teacher" | "admin";

/** Every role a person can hold. `teacher` is the baseline everyone has. */
export type StaffRole = "teacher" | "supervisor" | "admin";

/** What a person may apply to be. Admin is granted, never requested. */
export type ApplicantRole = "teacher" | "supervisor";

export type Academy = {
  id: string;
  slug: string;
  name_ar: string;
  name_en: string;
  description_ar: string | null;
  description_en: string | null;
  logo_path: string | null;
  primary_color: string;
  accent_color: string;
  is_active: boolean;
  created_at: string;
};

export type Teacher = {
  id: string;
  auth_user_id: string | null;
  name: string;
  phone: string | null;
  /** Digits-only form of the phone, generated by the DB. Unique per academy. */
  phone_key: string | null;
  gender_category: GenderCategory;
  /** Derived from `roles` by a trigger. Display only — see `TeacherRole`. */
  role: TeacherRole;
  /** Always contains "teacher"; may also carry "supervisor" and/or "admin". */
  roles: StaffRole[];
  is_active: boolean;
  academy_id: string;
  created_at: string;
};

export type Student = {
  id: string;
  name: string;
  father_name: string;
  phone: string | null;
  /** Digits-only form of `phone`, generated by the DB. Unique per academy. */
  phone_key: string | null;
  gender_category: GenderCategory;
  search_key: string;
  academy_id: string;
  created_at: string;
};

export type Circle = {
  id: string;
  teacher_id: string;
  name: string;
  type: CircleType;
  gender_category: GenderCategory;
  session_link: string;
  timezone: string;
  start_time: string;
  duration_minutes: number;
  /** PostgreSQL dow convention: 0 = Sunday … 6 = Saturday. */
  days_of_week: number[];
  registration_slug: string;
  is_active: boolean;
  academy_id: string;
  created_at: string;
  /** Null means unlimited. Enforced live by `join_circle()`, not a counter. */
  max_students: number | null;
};

export type AttendanceRecord = {
  id: string;
  student_id: string;
  circle_id: string;
  session_date: string;
  queue_order: number;
  joined_at: string;
  attendance_status: AttendanceStatus;
  recitation_status: RecitationStatus;
  created_at: string;
};

export type CirclePublicInfo = {
  id: string;
  name: string;
  type: CircleType;
  gender_category: GenderCategory;
  session_link: string;
  start_time: string;
  timezone: string;
  session_date: string;
  meets_today: boolean;
  academy_id: string;
  max_students: number | null;
};

export type StudentSearchResult = {
  id: string;
  name: string;
  father_name: string;
};

export type JoinCircleResult = {
  attendance_id: string;
  session_date: string;
  queue_order: number;
  already_joined: boolean;
};

export type QueueEntry = {
  attendance_id: string;
  student_id: string;
  name: string;
  father_name: string;
  queue_order: number;
  attendance_status: AttendanceStatus;
  recitation_status: RecitationStatus;
  joined_at: string;
};

export type TeacherTodayCircle = {
  id: string;
  name: string;
  type: CircleType;
  gender_category: GenderCategory;
  start_time: string;
  timezone: string;
  registration_slug: string;
  session_date: string;
  joined_count: number;
};

/** Confirms a name + phone match. Deliberately carries nothing else. */
export type TeacherLoginMatch = {
  teacher_id: string;
  is_active: boolean;
};

export type CircleTypeOption = {
  id: string;
  academy_id: string;
  slug: string;
  name_ar: string;
  name_en: string;
  is_active: boolean;
  /**
   * Whether a circle of this kind keeps a سجل تسميع — a mushaf range per
   * student. True for تصحيح التلاوة، تجويد and تسميع حر; false for حديث,
   * where the unit is a hadith and `student_unit_progress` records it.
   */
  records_recitation: boolean;
  created_at: string;
};

/**
 * The four kinds a حفظ circle distinguishes. مراجعة قريبة is recently
 * memorised ground, مراجعة بعيدة is old ground, تثبيت is the pass that makes
 * it permanent — collapsing them loses the only signal about retention.
 */
export type RecitationKind = "new" | "near_review" | "far_review" | "consolidation";

export type RecitationRating = "excellent" | "very_good" | "good" | "repeat";

/** One recorded turn: see supabase/migrations/20260913090000_recitation_log.sql. */
export type RecitationLog = {
  id: string;
  attendance_id: string | null;
  student_id: string;
  circle_id: string;
  session_date: string;
  teacher_id: string | null;
  kind: RecitationKind;
  from_surah: number;
  from_ayah: number;
  to_surah: number;
  to_ayah: number;
  rating: RecitationRating | null;
  /** لحن جلي — changes the word or the meaning. */
  major_errors: number;
  /** لحن خفي — a tajweed slip that does not change the meaning. */
  minor_errors: number;
  note: string | null;
  created_at: string;
  updated_at: string;
};

/** What `circle_recitation_logs` returns: today's logs, keyed by queue row. */
export type CircleRecitationLog = Pick<
  RecitationLog,
  | "attendance_id"
  | "student_id"
  | "kind"
  | "from_surah"
  | "from_ayah"
  | "to_surah"
  | "to_ayah"
  | "rating"
  | "major_errors"
  | "minor_errors"
  | "note"
>;

/**
 * A student's own view of one recorded turn, from `my_recitations`.
 *
 * Carries the circle and the معلمة's name and NOT the teacher's phone or the
 * attendance row — a student sees what she recited and who heard it, nothing
 * about the running of the circle.
 */
export type MyRecitation = {
  session_date: string;
  kind: RecitationKind;
  from_surah: number;
  from_ayah: number;
  to_surah: number;
  to_ayah: number;
  rating: RecitationRating | null;
  major_errors: number;
  minor_errors: number;
  circle_name: string;
  teacher_name: string | null;
};

/** One quiz her معلمة has open, from `my_quizzes`. */
export type MyQuiz = {
  quiz_id: string;
  title: string;
  instructions: string | null;
  duration_minutes: number | null;
  closes_at: string | null;
  max_attempts: number;
  question_count: number;
  circle_id: string;
  circle_name: string;
  registration_slug: string;
  teacher_name: string;
  attempts_used: number;
  last_status: 'in_progress' | 'submitted' | 'graded' | null;
  last_score: number | null;
  last_max_score: number | null;
  last_submitted_at: string | null;
};

/** One finished attempt, from `my_quiz_results`. */
export type MyQuizResult = {
  quiz_id: string;
  title: string;
  circle_name: string | null;
  status: 'submitted' | 'graded';
  score: number | null;
  max_score: number | null;
  submitted_at: string | null;
};

/** One circle a student has attended, from `my_circles`. */
export type MyCircle = {
  circle_id: string;
  circle_name: string;
  circle_type: CircleType;
  registration_slug: string;
  teacher_name: string;
  last_attended: string;
};

/** One ayah as the mushaf reader draws it. */
export type MushafAyah = {
  surah: number;
  ayah: number;
  juz: number;
  /** Whether this ayah carries a سجدة. The ۩ is already inside `text`. */
  sajda: boolean;
  /** Uthmani, verbatim from Tanzil. Never normalised, never added to. */
  text: string;
  /** True on ayah 1 — the reader draws a surah heading before it. */
  starts_surah: boolean;
};

/** One ayah of a range, for the self-test. */
export type QuranRangeAyah = {
  surah: number;
  ayah: number;
  page: number;
  juz: number;
  text: string;
};

/** Where a student stopped last time, so the next turn can prefill "من". */
export type LastRecitation = {
  to_surah: number;
  to_ayah: number;
  kind: RecitationKind;
  session_date: string;
};

/**
 * One published table on the public schedule page. Holds presentation only —
 * the days and names it renders are read live from `circles`.
 */
/**
 * What `academy_schedule` returns: an active circle as the public timetable
 * may see it — no `session_link`, and the teacher's name already joined in.
 */
export type ScheduleCircle = {
  id: string;
  name: string;
  type: CircleType;
  gender_category: GenderCategory;
  start_time: string;
  timezone: string;
  days_of_week: number[];
  registration_slug: string;
  teacher_name: string;
};

/**
 * A circle running at this moment, from `academy_live_circles`.
 *
 * Carries no `session_link` by design: the home page is public, and listing
 * every running circle's door would hand a stranger all of them at once.
 */
export type LiveCircle = {
  circle_id: string;
  circle_name: string;
  circle_type: CircleType;
  gender_category: GenderCategory;
  teacher_name: string;
  registration_slug: string;
  start_time: string;
  timezone: string;
  session_date: string;
  /** Whoever is reciting right now, or null between turns. */
  reciting_name: string | null;
  waiting_count: number;
  done_count: number;
  joined_count: number;
};

export type ScheduleBoard = {
  id: string;
  academy_id: string;
  circle_type: CircleType;
  /** Null covers both sections. */
  gender_category: GenderCategory | null;
  /**
   * Inclusive HH:MM bounds on a circle's `start_time`, each optional and each
   * open-ended alone — this is what separates a "2ظ" board from a "5م" one
   * when both cover the same circle type.
   */
  start_from: string | null;
  start_to: string | null;
  title_ar: string;
  title_en: string;
  note_ar: string | null;
  note_en: string | null;
  display_order: number;
  is_published: boolean;
  created_at: string;
};

/**
 * A curriculum ("الأربعون النووية") hangs off a circle *type*, not a circle —
 * so every حلقة حديث in the academy teaches from the same one, and adding
 * منهج تجويد later needs no new table and no new code.
 */
export type Curriculum = {
  id: string;
  academy_id: string;
  circle_type: CircleType;
  name_ar: string;
  name_en: string;
  description: string | null;
  display_order: number;
  is_active: boolean;
  created_at: string;
};

/**
 * One حديث, or one باب من متن. `narrator`, `source_book`, `source_ref` and
 * `grade` are the Hadith-shaped fields; a tajweed unit leaves them null.
 */
export type CurriculumUnit = {
  id: string;
  curriculum_id: string;
  position: number;
  title_ar: string;
  title_en: string;
  body: string | null;
  explanation: string | null;
  narrator: string | null;
  source_book: string | null;
  source_ref: string | null;
  grade: string | null;
  is_active: boolean;
  created_at: string;
};

export type MaterialKind = "image" | "pdf" | "slides" | "audio" | "video" | "link";

/**
 * Attached to a unit (shared by every circle teaching it) or to one circle.
 * Carries either an external `url` or a `storage_path` in the private
 * `materials` bucket — never both, enforced by `ck_materials_source`.
 */
export type Material = {
  id: string;
  academy_id: string;
  unit_id: string | null;
  circle_id: string | null;
  kind: MaterialKind;
  title: string;
  url: string | null;
  storage_path: string | null;
  position: number;
  uploaded_by: string | null;
  created_at: string;
};

/** What a circle is teaching on one day. The queue itself is unaffected. */
export type CircleSession = {
  circle_id: string;
  session_date: string;
  unit_id: string | null;
  note: string | null;
  updated_by: string | null;
  updated_at: string;
};

/** Today's lesson as a student may see it — no session link, no roster. */
export type CircleLessonRow = {
  unit_id: string | null;
  /** Named `unit_position` in SQL: `position` is reserved in RETURNS TABLE. */
  unit_position: number | null;
  title_ar: string | null;
  title_en: string | null;
  body: string | null;
  explanation: string | null;
  narrator: string | null;
  source_book: string | null;
  source_ref: string | null;
  grade: string | null;
  note: string | null;
  curriculum_ar: string | null;
  curriculum_en: string | null;
};

export type CircleMaterialRow = {
  id: string;
  kind: MaterialKind;
  title: string;
  url: string | null;
  storage_path: string | null;
  /** 'unit' — shared with every circle on this lesson; 'circle' — this one's. */
  scope: "unit" | "circle";
};

export type QuestionKind =
  | "mcq"
  | "multi"
  | "true_false"
  | "short_text"
  | "fill_blank";

/** Never `never`: a quiz whose results nobody may see is still gradeable. */
export type ShowResults = "never" | "after_submit" | "after_close";

/**
 * Scope runs widest to narrowest: `circle_type` is required, `curriculum_id`
 * and `circle_id` narrow it. A null `circle_id` means every circle of that
 * type — one quiz for all five حلقات حديث rather than five copies.
 */
export type Quiz = {
  id: string;
  academy_id: string;
  circle_type: CircleType;
  curriculum_id: string | null;
  circle_id: string | null;
  title: string;
  instructions: string | null;
  opens_at: string | null;
  closes_at: string | null;
  duration_minutes: number | null;
  pass_score: number;
  max_attempts: number;
  shuffle_questions: boolean;
  show_results: ShowResults;
  is_published: boolean;
  created_by: string | null;
  created_at: string;
};

export type QuizQuestion = {
  id: string;
  quiz_id: string;
  unit_id: string | null;
  position: number;
  kind: QuestionKind;
  prompt: string;
  media_url: string | null;
  points: number;
};

/**
 * `is_correct` is the answer key. It is readable only by staff — there is no
 * anon RLS policy on this table at all — and `quiz_for_student()` omits the
 * column by construction rather than by remembering to exclude it.
 */
export type QuizOption = {
  id: string;
  question_id: string;
  position: number;
  text: string;
  is_correct: boolean;
};

export type AttemptStatus = "in_progress" | "submitted" | "graded";

export type QuizAttempt = {
  id: string;
  quiz_id: string;
  student_id: string;
  circle_id: string | null;
  attempt_no: number;
  started_at: string;
  submitted_at: string | null;
  auto_score: number | null;
  manual_score: number | null;
  max_score: number | null;
  status: AttemptStatus;
};

export type QuizAnswer = {
  attempt_id: string;
  question_id: string;
  option_ids: string[] | null;
  text_answer: string | null;
  /** Null means not graded yet — the resting state of a written answer. */
  is_correct: boolean | null;
  awarded_points: number | null;
  answered_at: string;
};

/** A quiz open to this circle right now, as an anonymous student sees it. */
export type CircleQuizRow = {
  id: string;
  title: string;
  instructions: string | null;
  duration_minutes: number | null;
  closes_at: string | null;
  question_count: number;
};

export type StartAttemptRow = {
  attempt_id: string;
  resumed: boolean;
  expires_at: string | null;
};

/**
 * One row per (question, option) — the paper, flattened. Carries no
 * `is_correct`: that is the entire point of reading through the function.
 */
export type QuizForStudentRow = {
  question_id: string;
  /** Named `question_position` in SQL: `position` is reserved there. */
  question_position: number;
  kind: QuestionKind;
  prompt: string;
  media_url: string | null;
  points: number;
  option_id: string | null;
  option_text: string | null;
  chosen: boolean;
  text_answer: string | null;
};

export type SubmitAttemptRow = {
  auto_score: number;
  max_score: number;
  /** Written answers still waiting for a معلمة to mark them. */
  pending_count: number;
  pass_score: number;
  show_results: ShowResults;
};

/**
 * How far each student has got through a curriculum. Rows are written by the
 * `trg_attendance_records_progress` trigger when a معلمة marks a recitation
 * done, so the record is made at the moment it happens rather than inferred
 * later from a lesson that may since have been edited.
 */
export type ProgressReportRow = {
  student_id: string;
  student_name: string;
  father_name: string;
  gender_category: GenderCategory;
  curriculum_id: string;
  curriculum_ar: string;
  curriculum_en: string;
  units_done: number;
  units_total: number;
  last_unit_ar: string | null;
  last_at: string | null;
};

export type AttendanceReportRow = {
  student_id: string;
  student_name: string;
  father_name: string;
  gender_category: GenderCategory;
  sessions_joined: number;
  sessions_recited: number;
  sessions_not_recited: number;
};

type Insert<T, Optional extends keyof T> = Omit<T, Optional> &
  Partial<Pick<T, Optional>>;

/** Matches Supabase's generated shape: every table needs a Relationships key. */
type Empty = { [_ in never]: never };

export type Database = {
  public: {
    Tables: {
      academies: {
        Row: Academy;
        Insert: Insert<Academy, "id" | "created_at" | "is_active" | "description_ar" | "description_en" | "logo_path">;
        Update: Partial<Academy>;
        Relationships: [];
      };
      teachers: {
        Row: Teacher;
        // `phone_key` is a generated column — never written.
        Insert: Insert<
          Teacher,
          "id" | "created_at" | "role" | "roles" | "is_active" | "auth_user_id" | "phone_key"
        >;
        Update: Partial<Teacher>;
        Relationships: [];
      };
      students: {
        Row: Student;
        // `search_key` and `phone_key` are generated columns — never written.
        Insert: Insert<
          Student,
          "id" | "created_at" | "search_key" | "phone_key" | "academy_id"
        >;
        Update: Partial<Student>;
        Relationships: [];
      };
      circles: {
        Row: Circle;
        Insert: Insert<
          Circle,
          "id" | "created_at" | "is_active" | "timezone" | "duration_minutes" | "days_of_week" | "academy_id" | "max_students"
        >;
        Update: Partial<Circle>;
        Relationships: [];
      };
      attendance_records: {
        Row: AttendanceRecord;
        // Rows are created only by join_circle(); no RLS policy allows a direct
        // insert, so this type exists to satisfy the client, not to be used.
        Insert: Insert<AttendanceRecord, "id" | "created_at" | "joined_at">;
        Update: Partial<
          Pick<AttendanceRecord, "attendance_status" | "recitation_status" | "queue_order">
        >;
        Relationships: [];
      };
      recitation_logs: {
        Row: RecitationLog;
        // Rows are written only by record_recitation(); the policies allow a
        // direct insert, but nothing in the app takes that path — the RPC is
        // what derives student/circle/date from the queue row instead of
        // trusting the browser.
        Insert: Insert<RecitationLog, "id" | "created_at" | "updated_at">;
        Update: Partial<RecitationLog>;
        Relationships: [];
      };
      circle_types: {
        Row: CircleTypeOption;
        Insert: Insert<
          CircleTypeOption,
          "id" | "created_at" | "is_active" | "records_recitation"
        >;
        Update: Partial<CircleTypeOption>;
        Relationships: [];
      };
      schedule_boards: {
        Row: ScheduleBoard;
        Insert: Insert<
          ScheduleBoard,
          "id" | "created_at" | "is_published" | "display_order"
        >;
        Update: Partial<ScheduleBoard>;
        Relationships: [];
      };
      curricula: {
        Row: Curriculum;
        Insert: Insert<
          Curriculum,
          "id" | "created_at" | "is_active" | "display_order" | "description"
        >;
        Update: Partial<Curriculum>;
        Relationships: [];
      };
      curriculum_units: {
        Row: CurriculumUnit;
        Insert: Insert<
          CurriculumUnit,
          | "id" | "created_at" | "is_active" | "body" | "explanation"
          | "narrator" | "source_book" | "source_ref" | "grade"
        >;
        Update: Partial<CurriculumUnit>;
        Relationships: [];
      };
      materials: {
        Row: Material;
        Insert: Insert<
          Material,
          | "id" | "created_at" | "position" | "url" | "storage_path"
          | "unit_id" | "circle_id" | "uploaded_by"
        >;
        Update: Partial<Material>;
        Relationships: [];
      };
      circle_sessions: {
        Row: CircleSession;
        Insert: Insert<
          CircleSession,
          "updated_at" | "unit_id" | "note" | "updated_by"
        >;
        Update: Partial<CircleSession>;
        Relationships: [];
      };
      quizzes: {
        Row: Quiz;
        Insert: Insert<
          Quiz,
          | "id" | "created_at" | "is_published" | "pass_score" | "max_attempts"
          | "shuffle_questions" | "show_results" | "instructions" | "opens_at"
          | "closes_at" | "duration_minutes" | "curriculum_id" | "circle_id"
          | "created_by"
        >;
        Update: Partial<Quiz>;
        Relationships: [];
      };
      quiz_questions: {
        Row: QuizQuestion;
        Insert: Insert<QuizQuestion, "id" | "unit_id" | "media_url" | "points">;
        Update: Partial<QuizQuestion>;
        Relationships: [];
      };
      quiz_options: {
        Row: QuizOption;
        Insert: Insert<QuizOption, "id" | "is_correct">;
        Update: Partial<QuizOption>;
        Relationships: [];
      };
      quiz_attempts: {
        Row: QuizAttempt;
        // Created only by start_quiz_attempt(); no policy allows a direct
        // insert. Present to satisfy the client, not to be used.
        Insert: Insert<
          QuizAttempt,
          | "id" | "started_at" | "submitted_at" | "auto_score" | "manual_score"
          | "max_score" | "status" | "attempt_no" | "circle_id"
        >;
        Update: Partial<QuizAttempt>;
        Relationships: [];
      };
      quiz_answers: {
        Row: QuizAnswer;
        Insert: Insert<
          QuizAnswer,
          "option_ids" | "text_answer" | "is_correct" | "awarded_points" | "answered_at"
        >;
        Update: Partial<QuizAnswer>;
        Relationships: [];
      };
    };
    Views: Empty;
    Functions: {
      get_academy: {
        Args: { p_slug: string };
        Returns: Academy[];
      };
      circle_public_info: {
        Args: { p_slug: string };
        Returns: CirclePublicInfo[];
      };
      academy_schedule: {
        Args: { p_academy_id: string };
        Returns: ScheduleCircle[];
      };
      academy_live_circles: {
        Args: { p_academy_id: string };
        Returns: LiveCircle[];
      };
      search_students: {
        Args: { p_slug: string; p_query: string };
        Returns: StudentSearchResult[];
      };
      find_similar_students: {
        Args: { p_name: string; p_father_name: string; p_gender: GenderCategory; p_academy_id: string };
        Returns: StudentSearchResult[];
      };
      join_circle: {
        Args: { p_slug: string; p_student_id: string };
        Returns: JoinCircleResult[];
      };
      circle_queue: {
        Args: { p_slug: string };
        Returns: QueueEntry[];
      };
      teacher_today_circles: {
        Args: Record<PropertyKey, never>;
        Returns: TeacherTodayCircle[];
      };
      reorder_queue: {
        Args: {
          p_circle_id: string;
          p_session_date: string;
          p_student_ids: string[];
        };
        Returns: undefined;
      };
      record_recitation: {
        Args: {
          p_attendance_id: string;
          p_kind: RecitationKind;
          p_from_surah: number;
          p_from_ayah: number;
          p_to_surah: number;
          p_to_ayah: number;
          p_rating?: RecitationRating | null;
          p_major_errors?: number;
          p_minor_errors?: number;
          p_note?: string | null;
          p_finish_turn?: boolean;
        };
        /** The log's id. */
        Returns: string;
      };
      last_recitation: {
        Args: { p_student_id: string };
        Returns: LastRecitation[];
      };
      circle_recitation_logs: {
        Args: { p_circle_id: string; p_session_date: string };
        Returns: CircleRecitationLog[];
      };
      mushaf_page: {
        Args: { p_page: number };
        Returns: MushafAyah[];
      };
      mushaf_page_of: {
        Args: { p_surah: number; p_ayah: number };
        Returns: number;
      };
      quran_range: {
        Args: {
          p_from_surah: number;
          p_from_ayah: number;
          p_to_surah: number;
          p_to_ayah: number;
        };
        Returns: QuranRangeAyah[];
      };
      find_me: {
        Args: { p_academy_slug: string; p_name: string; p_phone: string };
        /** At most one row — never a list. See the migration for why. */
        Returns: StudentSearchResult[];
      };
      my_recitations: {
        Args: { p_student_id: string; p_phone: string };
        Returns: MyRecitation[];
      };
      my_circles: {
        Args: { p_student_id: string; p_phone: string };
        Returns: MyCircle[];
      };
      my_quizzes: {
        Args: { p_student_id: string; p_phone: string };
        Returns: MyQuiz[];
      };
      my_quiz_results: {
        Args: { p_student_id: string; p_phone: string };
        Returns: MyQuizResult[];
      };
      teacher_login: {
        Args: { p_academy_id: string; p_name: string; p_phone: string };
        Returns: TeacherLoginMatch[];
      };
      link_teacher_auth: {
        Args: { p_teacher_id: string };
        Returns: undefined;
      };
      register_teacher: {
        Args: {
          p_academy_id: string;
          p_name: string;
          p_phone: string;
          p_role: ApplicantRole;
          p_gender?: GenderCategory;
        };
        Returns: undefined;
      };
      attendance_report: {
        Args: {
          p_from: string;
          p_to: string;
          p_gender?: GenderCategory | null;
          p_teacher_ids?: string[] | null;
          p_academy_id?: string | null;
          p_circle_type?: CircleType | null;
        };
        Returns: AttendanceReportRow[];
      };
      circle_lesson: {
        Args: { p_slug: string };
        Returns: CircleLessonRow[];
      };
      circle_materials: {
        Args: { p_slug: string };
        Returns: CircleMaterialRow[];
      };
      circle_quizzes: {
        Args: { p_slug: string };
        Returns: CircleQuizRow[];
      };
      start_quiz_attempt: {
        Args: {
          p_slug: string;
          p_quiz_id: string;
          p_student_id: string;
          p_phone: string;
        };
        Returns: StartAttemptRow[];
      };
      quiz_for_student: {
        Args: { p_attempt_id: string };
        Returns: QuizForStudentRow[];
      };
      save_quiz_answer: {
        Args: {
          p_attempt_id: string;
          p_question_id: string;
          p_option_ids?: string[] | null;
          p_text?: string | null;
        };
        Returns: undefined;
      };
      submit_quiz_attempt: {
        Args: { p_attempt_id: string };
        Returns: SubmitAttemptRow[];
      };
      curriculum_progress_report: {
        Args: {
          p_academy_id: string;
          p_curriculum_id?: string | null;
          p_circle_id?: string | null;
          p_gender?: GenderCategory | null;
        };
        Returns: ProgressReportRow[];
      };
      grade_written_answer: {
        Args: {
          p_attempt_id: string;
          p_question_id: string;
          p_is_correct: boolean;
          p_points?: number | null;
        };
        Returns: { auto_score: number; max_score: number; pending_count: number }[];
      };
    };
    Enums: Empty;
    CompositeTypes: Empty;
  };
};
