// GENERATED by scripts/generate-quran-metadata.mjs — do not edit by hand.
//
// Names are verbatim from a published Uthmani edition; see the generator for
// why they are not typed out here. Source: https://api.alquran.cloud/v1/surah

export type Surah = {
  number: number;
  /** Uthmani orthography, without the leading word سورة. Display only. */
  name: string;
  /**
   * The same name with every mark stripped, so typing "الكهف" finds ٱلْكَهۡفِ.
   * A search key — never shown, never a substitute for `name`.
   */
  plain: string;
  englishName: string;
  /** Upper bound for an ayah number in this surah. */
  ayahs: number;
};

export const SURAHS: readonly Surah[] = [
  { number: 1, name: "ٱلْفَاتِحَةِ", plain: "الفاتحه", englishName: "Al-Faatiha", ayahs: 7 },
  { number: 2, name: "البَقَرَةِ", plain: "البقره", englishName: "Al-Baqara", ayahs: 286 },
  { number: 3, name: "آلِ عِمۡرَانَ", plain: "ال عمران", englishName: "Aal-i-Imraan", ayahs: 200 },
  { number: 4, name: "النِّسَاءِ", plain: "النساء", englishName: "An-Nisaa", ayahs: 176 },
  { number: 5, name: "المَائـِدَةِ", plain: "المائده", englishName: "Al-Maaida", ayahs: 120 },
  { number: 6, name: "الأَنۡعَامِ", plain: "الانعام", englishName: "Al-An'aam", ayahs: 165 },
  { number: 7, name: "الأَعۡرَافِ", plain: "الاعراف", englishName: "Al-A'raaf", ayahs: 206 },
  { number: 8, name: "الأَنفَالِ", plain: "الانفال", englishName: "Al-Anfaal", ayahs: 75 },
  { number: 9, name: "التَّوۡبَةِ", plain: "التوبه", englishName: "At-Tawba", ayahs: 129 },
  { number: 10, name: "يُونُسَ", plain: "يونس", englishName: "Yunus", ayahs: 109 },
  { number: 11, name: "هُودٍ", plain: "هود", englishName: "Hud", ayahs: 123 },
  { number: 12, name: "يُوسُفَ", plain: "يوسف", englishName: "Yusuf", ayahs: 111 },
  { number: 13, name: "الرَّعۡدِ", plain: "الرعد", englishName: "Ar-Ra'd", ayahs: 43 },
  { number: 14, name: "إِبۡرَاهِيمَ", plain: "ابراهيم", englishName: "Ibrahim", ayahs: 52 },
  { number: 15, name: "الحِجۡرِ", plain: "الحجر", englishName: "Al-Hijr", ayahs: 99 },
  { number: 16, name: "النَّحۡلِ", plain: "النحل", englishName: "An-Nahl", ayahs: 128 },
  { number: 17, name: "الإِسۡرَاءِ", plain: "الاسراء", englishName: "Al-Israa", ayahs: 111 },
  { number: 18, name: "الكَهۡفِ", plain: "الكهف", englishName: "Al-Kahf", ayahs: 110 },
  { number: 19, name: "مَرۡيَمَ", plain: "مريم", englishName: "Maryam", ayahs: 98 },
  { number: 20, name: "طه", plain: "طه", englishName: "Taa-Haa", ayahs: 135 },
  { number: 21, name: "الأَنبِيَاءِ", plain: "الانبياء", englishName: "Al-Anbiyaa", ayahs: 112 },
  { number: 22, name: "الحَجِّ", plain: "الحج", englishName: "Al-Hajj", ayahs: 78 },
  { number: 23, name: "المُؤۡمِنُونَ", plain: "المؤمنون", englishName: "Al-Muminoon", ayahs: 118 },
  { number: 24, name: "النُّورِ", plain: "النور", englishName: "An-Noor", ayahs: 64 },
  { number: 25, name: "الفُرۡقَانِ", plain: "الفرقان", englishName: "Al-Furqaan", ayahs: 77 },
  { number: 26, name: "الشُّعَرَاءِ", plain: "الشعراء", englishName: "Ash-Shu'araa", ayahs: 227 },
  { number: 27, name: "النَّمۡلِ", plain: "النمل", englishName: "An-Naml", ayahs: 93 },
  { number: 28, name: "القَصَصِ", plain: "القصص", englishName: "Al-Qasas", ayahs: 88 },
  { number: 29, name: "العَنكَبُوتِ", plain: "العنكبوت", englishName: "Al-Ankaboot", ayahs: 69 },
  { number: 30, name: "الرُّومِ", plain: "الروم", englishName: "Ar-Room", ayahs: 60 },
  { number: 31, name: "لُقۡمَانَ", plain: "لقمان", englishName: "Luqman", ayahs: 34 },
  { number: 32, name: "السَّجۡدَةِ", plain: "السجده", englishName: "As-Sajda", ayahs: 30 },
  { number: 33, name: "الأَحۡزَابِ", plain: "الاحزاب", englishName: "Al-Ahzaab", ayahs: 73 },
  { number: 34, name: "سَبَإٍ", plain: "سبا", englishName: "Saba", ayahs: 54 },
  { number: 35, name: "فَاطِرٍ", plain: "فاطر", englishName: "Faatir", ayahs: 45 },
  { number: 36, name: "يسٓ", plain: "يس", englishName: "Yaseen", ayahs: 83 },
  { number: 37, name: "الصَّافَّاتِ", plain: "الصافات", englishName: "As-Saaffaat", ayahs: 182 },
  { number: 38, name: "صٓ", plain: "ص", englishName: "Saad", ayahs: 88 },
  { number: 39, name: "الزُّمَرِ", plain: "الزمر", englishName: "Az-Zumar", ayahs: 75 },
  { number: 40, name: "غَافِرٍ", plain: "غافر", englishName: "Ghafir", ayahs: 85 },
  { number: 41, name: "فُصِّلَتۡ", plain: "فصلت", englishName: "Fussilat", ayahs: 54 },
  { number: 42, name: "الشُّورَىٰ", plain: "الشوري", englishName: "Ash-Shura", ayahs: 53 },
  { number: 43, name: "الزُّخۡرُفِ", plain: "الزخرف", englishName: "Az-Zukhruf", ayahs: 89 },
  { number: 44, name: "الدُّخَانِ", plain: "الدخان", englishName: "Ad-Dukhaan", ayahs: 59 },
  { number: 45, name: "الجَاثِيَةِ", plain: "الجاثيه", englishName: "Al-Jaathiya", ayahs: 37 },
  { number: 46, name: "الأَحۡقَافِ", plain: "الاحقاف", englishName: "Al-Ahqaf", ayahs: 35 },
  { number: 47, name: "مُحَمَّدٍ", plain: "محمد", englishName: "Muhammad", ayahs: 38 },
  { number: 48, name: "الفَتۡحِ", plain: "الفتح", englishName: "Al-Fath", ayahs: 29 },
  { number: 49, name: "الحُجُرَاتِ", plain: "الحجرات", englishName: "Al-Hujuraat", ayahs: 18 },
  { number: 50, name: "قٓ", plain: "ق", englishName: "Qaaf", ayahs: 45 },
  { number: 51, name: "الذَّارِيَاتِ", plain: "الذاريات", englishName: "Adh-Dhaariyat", ayahs: 60 },
  { number: 52, name: "الطُّورِ", plain: "الطور", englishName: "At-Tur", ayahs: 49 },
  { number: 53, name: "النَّجۡمِ", plain: "النجم", englishName: "An-Najm", ayahs: 62 },
  { number: 54, name: "القَمَرِ", plain: "القمر", englishName: "Al-Qamar", ayahs: 55 },
  { number: 55, name: "الرَّحۡمَٰن", plain: "الرحمن", englishName: "Ar-Rahmaan", ayahs: 78 },
  { number: 56, name: "الوَاقِعَةِ", plain: "الواقعه", englishName: "Al-Waaqia", ayahs: 96 },
  { number: 57, name: "الحَدِيدِ", plain: "الحديد", englishName: "Al-Hadid", ayahs: 29 },
  { number: 58, name: "المُجَادلَةِ", plain: "المجادله", englishName: "Al-Mujaadila", ayahs: 22 },
  { number: 59, name: "الحَشۡرِ", plain: "الحشر", englishName: "Al-Hashr", ayahs: 24 },
  { number: 60, name: "المُمۡتَحنَةِ", plain: "الممتحنه", englishName: "Al-Mumtahana", ayahs: 13 },
  { number: 61, name: "الصَّفِّ", plain: "الصف", englishName: "As-Saff", ayahs: 14 },
  { number: 62, name: "الجُمُعَةِ", plain: "الجمعه", englishName: "Al-Jumu'a", ayahs: 11 },
  { number: 63, name: "المُنَافِقُونَ", plain: "المنافقون", englishName: "Al-Munaafiqoon", ayahs: 11 },
  { number: 64, name: "التَّغَابُنِ", plain: "التغابن", englishName: "At-Taghaabun", ayahs: 18 },
  { number: 65, name: "الطَّلَاقِ", plain: "الطلاق", englishName: "At-Talaaq", ayahs: 12 },
  { number: 66, name: "التَّحۡرِيمِ", plain: "التحريم", englishName: "At-Tahrim", ayahs: 12 },
  { number: 67, name: "المُلۡكِ", plain: "الملك", englishName: "Al-Mulk", ayahs: 30 },
  { number: 68, name: "القَلَمِ", plain: "القلم", englishName: "Al-Qalam", ayahs: 52 },
  { number: 69, name: "الحَاقَّةِ", plain: "الحاقه", englishName: "Al-Haaqqa", ayahs: 52 },
  { number: 70, name: "المَعَارِجِ", plain: "المعارج", englishName: "Al-Ma'aarij", ayahs: 44 },
  { number: 71, name: "نُوحٍ", plain: "نوح", englishName: "Nooh", ayahs: 28 },
  { number: 72, name: "الجِنِّ", plain: "الجن", englishName: "Al-Jinn", ayahs: 28 },
  { number: 73, name: "المُزَّمِّلِ", plain: "المزمل", englishName: "Al-Muzzammil", ayahs: 20 },
  { number: 74, name: "المُدَّثِّرِ", plain: "المدثر", englishName: "Al-Muddaththir", ayahs: 56 },
  { number: 75, name: "القِيَامَةِ", plain: "القيامه", englishName: "Al-Qiyaama", ayahs: 40 },
  { number: 76, name: "الإِنسَانِ", plain: "الانسان", englishName: "Al-Insaan", ayahs: 31 },
  { number: 77, name: "المُرۡسَلَاتِ", plain: "المرسلات", englishName: "Al-Mursalaat", ayahs: 50 },
  { number: 78, name: "النَّبَإِ", plain: "النبا", englishName: "An-Naba", ayahs: 40 },
  { number: 79, name: "النَّازِعَاتِ", plain: "النازعات", englishName: "An-Naazi'aat", ayahs: 46 },
  { number: 80, name: "عَبَسَ", plain: "عبس", englishName: "Abasa", ayahs: 42 },
  { number: 81, name: "التَّكۡوِيرِ", plain: "التكوير", englishName: "At-Takwir", ayahs: 29 },
  { number: 82, name: "الانفِطَارِ", plain: "الانفطار", englishName: "Al-Infitaar", ayahs: 19 },
  { number: 83, name: "المُطَفِّفِينَ", plain: "المطففين", englishName: "Al-Mutaffifin", ayahs: 36 },
  { number: 84, name: "الانشِقَاقِ", plain: "الانشقاق", englishName: "Al-Inshiqaaq", ayahs: 25 },
  { number: 85, name: "البُرُوجِ", plain: "البروج", englishName: "Al-Burooj", ayahs: 22 },
  { number: 86, name: "الطَّارِقِ", plain: "الطارق", englishName: "At-Taariq", ayahs: 17 },
  { number: 87, name: "الأَعۡلَىٰ", plain: "الاعلي", englishName: "Al-A'laa", ayahs: 19 },
  { number: 88, name: "الغَاشِيَةِ", plain: "الغاشيه", englishName: "Al-Ghaashiya", ayahs: 26 },
  { number: 89, name: "الفَجۡرِ", plain: "الفجر", englishName: "Al-Fajr", ayahs: 30 },
  { number: 90, name: "البَلَدِ", plain: "البلد", englishName: "Al-Balad", ayahs: 20 },
  { number: 91, name: "الشَّمۡسِ", plain: "الشمس", englishName: "Ash-Shams", ayahs: 15 },
  { number: 92, name: "اللَّيۡلِ", plain: "الليل", englishName: "Al-Lail", ayahs: 21 },
  { number: 93, name: "الضُّحَىٰ", plain: "الضحي", englishName: "Ad-Dhuhaa", ayahs: 11 },
  { number: 94, name: "الشَّرۡحِ", plain: "الشرح", englishName: "Ash-Sharh", ayahs: 8 },
  { number: 95, name: "التِّينِ", plain: "التين", englishName: "At-Tin", ayahs: 8 },
  { number: 96, name: "العَلَقِ", plain: "العلق", englishName: "Al-Alaq", ayahs: 19 },
  { number: 97, name: "القَدۡرِ", plain: "القدر", englishName: "Al-Qadr", ayahs: 5 },
  { number: 98, name: "البَيِّنَةِ", plain: "البينه", englishName: "Al-Bayyina", ayahs: 8 },
  { number: 99, name: "الزَّلۡزَلَةِ", plain: "الزلزله", englishName: "Az-Zalzala", ayahs: 8 },
  { number: 100, name: "العَادِيَاتِ", plain: "العاديات", englishName: "Al-Aadiyaat", ayahs: 11 },
  { number: 101, name: "القَارِعَةِ", plain: "القارعه", englishName: "Al-Qaari'a", ayahs: 11 },
  { number: 102, name: "التَّكَاثُرِ", plain: "التكاثر", englishName: "At-Takaathur", ayahs: 8 },
  { number: 103, name: "العَصۡرِ", plain: "العصر", englishName: "Al-Asr", ayahs: 3 },
  { number: 104, name: "الهُمَزَةِ", plain: "الهمزه", englishName: "Al-Humaza", ayahs: 9 },
  { number: 105, name: "الفِيلِ", plain: "الفيل", englishName: "Al-Fil", ayahs: 5 },
  { number: 106, name: "قُرَيۡشٍ", plain: "قريش", englishName: "Quraish", ayahs: 4 },
  { number: 107, name: "المَاعُونِ", plain: "الماعون", englishName: "Al-Maa'un", ayahs: 7 },
  { number: 108, name: "الكَوۡثَرِ", plain: "الكوثر", englishName: "Al-Kawthar", ayahs: 3 },
  { number: 109, name: "الكَافِرُونَ", plain: "الكافرون", englishName: "Al-Kaafiroon", ayahs: 6 },
  { number: 110, name: "النَّصۡرِ", plain: "النصر", englishName: "An-Nasr", ayahs: 3 },
  { number: 111, name: "المَسَدِ", plain: "المسد", englishName: "Al-Masad", ayahs: 5 },
  { number: 112, name: "الإِخۡلَاصِ", plain: "الاخلاص", englishName: "Al-Ikhlaas", ayahs: 4 },
  { number: 113, name: "الفَلَقِ", plain: "الفلق", englishName: "Al-Falaq", ayahs: 5 },
  { number: 114, name: "النَّاسِ", plain: "الناس", englishName: "An-Naas", ayahs: 6 },
];

/** Total ayahs in the Quran — the denominator for "how much of it". */
export const TOTAL_AYAHS = SURAHS.reduce((sum, surah) => sum + surah.ayahs, 0);

export function surahByNumber(number: number): Surah | undefined {
  return SURAHS[number - 1];
}
