-- المتشابهات — ayat that are near-identical but part on a word.
--
-- «أَوَلَمْ يَرَوْا۟» in الروم against «أَوَلَمْ يَعْلَمُوٓا۟» in الزمر.
-- «مَا كَسَبُوا۟» in الزمر against «مَا عَمِلُوا۟» in الجاثية.
-- «نَجَّيْنَٰكُم» in البقرة against «أَنجَيْنَٰكُم» in الأعراف.
--
-- This is the hardest obstacle in serious حفظ and whole books are organised
-- around it. It is also the one drill a machine can produce and a معلمة cannot
-- write by hand: finding them needs every ayah compared against every other.
--
-- The rows are computed once by scripts/generate-mutashabihat.mjs and stored,
-- not derived at request time — a similarity pass over the whole mushaf is not
-- something to run while a student waits.
--
-- NO TEXT IS STORED HERE. The table holds references into `quran_ayahs` plus
-- the two differing words, and the words themselves are copied verbatim from
-- the stored ayah at an index the generator proves lines up. The question is
-- rendered from `quran_ayahs` at read time, so the scripture has exactly one
-- home.

create table public.quran_mutashabihat (
  id bigint generated always as identity primary key,

  -- The ayah the question is asked about.
  a_surah smallint not null check (a_surah between 1 and 114),
  a_ayah  smallint not null check (a_ayah >= 1),
  -- Its near-twin, which supplies the wrong answer.
  b_surah smallint not null check (b_surah between 1 and 114),
  b_ayah  smallint not null check (b_ayah >= 1),

  -- Word-level, 0–1. Below 0.6 the two are not confusable; 1.0 would mean
  -- identical, which is a different phenomenon (a refrain) and is excluded.
  similarity numeric(4,3) not null check (similarity > 0.5 and similarity < 1),

  -- Where they part: the index of the first differing word in each, counting
  -- only real words — standalone waqf signs are tokens but not words, and the
  -- generator drops them from both sides together so these indexes address
  -- the same position in each ayah.
  a_word_index smallint not null check (a_word_index >= 0),
  b_word_index smallint not null check (b_word_index >= 0),

  -- The two words, verbatim. Stored so the question can offer the wrong answer
  -- without a second lookup; still rendered from the ayah itself.
  a_word text not null check (btrim(a_word) <> ''),
  b_word text not null check (btrim(b_word) <> ''),

  constraint mutashabihat_distinct check ((a_surah, a_ayah) <> (b_surah, b_ayah)),
  constraint mutashabihat_words_differ check (a_word <> b_word),
  constraint fk_mutashabihat_a foreign key (a_surah, a_ayah)
    references public.quran_ayahs (surah, ayah) on delete cascade,
  constraint fk_mutashabihat_b foreign key (b_surah, b_ayah)
    references public.quran_ayahs (surah, ayah) on delete cascade
);

create index idx_mutashabihat_a on public.quran_mutashabihat (a_surah, a_ayah);

alter table public.quran_mutashabihat enable row level security;

-- Readable by everyone, writable by nobody through the API — the same posture
-- as `quran_ayahs`, and for the same reason: it is derived from scripture and
-- is regenerated by a script, never edited from inside the app.
create policy mutashabihat_read on public.quran_mutashabihat
  for select to anon, authenticated
  using (true);

-- =============================================================================
-- The question
-- =============================================================================

-- Pairs whose FIRST ayah falls in a juz range, with both texts joined in so
-- the caller never has to look scripture up separately.
--
-- Randomised in the database rather than by fetching everything and choosing
-- in the browser: the whole table is small, but shipping all of it to pick ten
-- would mean a student's phone downloading every متشابه in the Quran to sit a
-- ten-question test.
create or replace function public.mutashabihat_questions(
  p_from_juz int,
  p_to_juz   int,
  p_limit    int default 10
)
returns table (
  a_surah      smallint,
  a_ayah       smallint,
  a_text       text,
  a_page       smallint,
  a_word_index smallint,
  a_word       text,
  b_surah      smallint,
  b_ayah       smallint,
  b_word       text,
  similarity   numeric
)
language sql stable security definer set search_path = public
as $$
  select m.a_surah, m.a_ayah, qa.text, qa.page,
         m.a_word_index, m.a_word,
         m.b_surah, m.b_ayah, m.b_word,
         m.similarity
    from public.quran_mutashabihat m
    join public.quran_ayahs qa
      on qa.surah = m.a_surah and qa.ayah = m.a_ayah
   where qa.juz between p_from_juz and p_to_juz
   order by random()
   limit least(greatest(coalesce(p_limit, 10), 1), 30);
$$;

revoke execute on function public.mutashabihat_questions(int, int, int) from public;
grant  execute on function public.mutashabihat_questions(int, int, int) to anon, authenticated;

comment on table public.quran_mutashabihat is
  'Near-identical ayah pairs and the word they part on. Generated, never edited.';
